import { ImageSourcePropType } from 'react-native';

const data : {
    id:number,
    name:string,
    img : ImageSourcePropType,
    phone:string,
    money:string,
    } [] = [
            {
                id:1,
                name : 'Akhnaton',
                img : require('../../../images/Akhnaton.jpg'),
                phone:'01753644321',
                money:'800,000',
            },
            {
                id:2,
                name : 'Hatshepsut',
                img : require('../../../images/hatsh.jpg'),
                phone:'01753644321',
                money:'800,000',
            },
            {
                id:3,
                name : 'Tutankhamon',
                img : require('../../../images/Tot.jpg'),
                phone:'01753644321',
                money:'800,000',
            },
            {
                id:4,
                name : 'Thutmose',
                img : require('../../../images/Thut.jpg'),
                phone:'01753644321',
                money:'800,000',
            },
            {
                id:5,
                name : 'Ramses ii',
                img : require('../../../images/rams.jpg'),
                phone:'01753644321',
                money:'800,000',
            },
            {
                id:6,
                name : 'Tutankhamon',
                img : require('../../../images/Tot.jpg'),
                phone:'01753644321',
                money:'800,000',
            },
            {
                id:7,
                name : 'Thutmose',
                img : require('../../../images/Thut.jpg'),
                phone:'01753644321',
                money:'800,000',
            },
            {
                id:8,
                name : 'Ramses ii',
                img : require('../../../images/rams.jpg'),
                phone:'01753644321',
                money:'800,000',
            },
            {
                id:9,
                name : 'Thutmose',
                img : require('../../../images/Thut.jpg'),
                phone:'01753644321',
                money:'800,000',
            },
            {
                id:10,
                name : 'Ramses ii',
                img : require('../../../images/rams.jpg'),
                phone:'01753644321',
                money:'800,000',
            },
            {
                id:11,
                name : 'Thutmose',
                img : require('../../../images/Thut.jpg'),
                phone:'01753644321',
                money:'800,000',
            },
            {
                id:12,
                name : 'Akhnaton',
                img : require('../../../images/Akhnaton.jpg'),
                phone:'01753644321',
                money:'800,000',
            },
        ];
export default data;
